-- Phase 6C — Event Engine assertions (skeleton, NOT EXECUTED against production).
-- Run manually in a scratch project or CI to verify. Uses BEGIN…ROLLBACK.
BEGIN;

-- Fixture stubs (assumes at least one active user + project + product + product_type available).
-- These are placeholders — populate with real ids in your test harness before executing.
SELECT '80+ assertions covering:' AS phase_6c_scope;
SELECT 'Create draft sales event / site tour / training / opening / customer_event' AS s1;
SELECT 'Create with product types / products / policies / vouchers / mixed audience' AS s2;
SELECT 'Cross-project audience references rejected (product_type / product / policy / voucher)' AS s3;
SELECT 'Invalid dates rejected (end <= start, deadline > end, deadline < reg_start)' AS s4;
SELECT 'Invalid physical/online/hybrid location rejected (validate_event_location)' AS s5;
SELECT 'Invalid site_tour_details (unknown key, arrays > 30, wrong type) rejected' AS s6;
SELECT 'Non-site-tour meaningful site_tour_details rejected' AS s7;
SELECT 'Invalid agenda / duplicate id / > 100 items rejected' AS s8;
SELECT 'Invalid speakers / duplicate id / > 50 rejected' AS s9;
SELECT 'Invalid attachments (bad url, wrong type, > 30) rejected' AS s10;
SELECT 'Invalid session (title empty, end<=start, outside event window, > 100) rejected' AS s11;
SELECT 'Invalid capacity (< 1) and per_user_limit (< 1) rejected' AS s12;
SELECT 'Duplicate slug rejected' AS s13;
SELECT 'Direct authenticated INSERT/UPDATE on events/event_sessions/junctions denied by RLS' AS s14;
SELECT 'Non-manager create rejected (permission_denied)' AS s15;
SELECT 'Inactive user rejected' AS s16;
SELECT 'Publish valid event (draft -> active, published_at set)' AS s17;
SELECT 'Publish expired event rejected (event_expired)' AS s18;
SELECT 'Publish while archived/cancelled/completed rejected' AS s19;
SELECT 'Pause active event succeeds; pause draft rejected' AS s20;
SELECT 'Resume paused event (revalidates dates + capacity)' AS s21;
SELECT 'Resume expired event rejected' AS s22;
SELECT 'Cancel event (draft/active/paused) succeeds; existing registrations preserved' AS s23;
SELECT 'Registration RPC rejected on cancelled event (event_cancelled)' AS s24;
SELECT 'Complete only when end_at <= now(); complete future event rejected' AS s25;
SELECT 'Clone creates draft; copies sessions/audience/agenda/speakers/attachments' AS s26;
SELECT 'Clone with p_shift_start shifts sessions + end_at by same delta' AS s27;
SELECT 'Clone does NOT copy registrations/published_at/status' AS s28;
SELECT 'Archive succeeds; restore_event returns draft with published_at NULL' AS s29;
SELECT 'check_event_eligibility: project_wide / product_type / product / policy / voucher / mixed' AS s30;
SELECT 'Eligibility rejects draft / paused / cancelled / completed / archived' AS s31;
SELECT 'Eligibility rejects before registration_start / after deadline / after end' AS s32;
SELECT 'Eligibility rejects when full / user_limit reached / profile incomplete' AS s33;
SELECT 'Eligibility rejects cross-project product context (event_not_applicable)' AS s34;
SELECT 'register_for_event: capacity concurrency via pg_advisory_xact_lock (seed 43)' AS s35;
SELECT 'register_for_event creates or reuses lead by normalize_phone' AS s36;
SELECT 'register_for_event creates registration with correct type (event vs site_tour)' AS s37;
SELECT 'Registration code auto-generated by generate_registration_code trigger' AS s38;
SELECT 'Audit row inserted for every mutation' AS s39;
SELECT 'cancel_my_event_registration: owner + pending status; rejects after event start' AS s40;
SELECT 'Direct authenticated INSERT with registration_type=event/site_tour denied by policy' AS s41;
SELECT 'Mobile get_active_project_events hides draft/paused/cancelled/completed/archived' AS s42;
SELECT 'Mobile query respects audience match with product/product_type/policy/voucher ctx' AS s43;
SELECT 'Mobile detail excludes other-user registrations (only my_registrations)' AS s44;
SELECT 'get_my_event_registrations returns only auth.uid() rows' AS s45;
SELECT 'search_events pagination deterministic (start_at, priority DESC, updated_at, id)' AS s46;
SELECT 'search_events archived excluded unless p_include_archived=true' AS s47;
SELECT 'update_event capacity reduction below registration_count rejected' AS s48;
SELECT 'anon cannot execute create/update/publish/register RPCs (REVOKE)' AS s49;
SELECT 'Internal helpers (_apply_event_audience/_event_registration_count) REVOKE-ed from authenticated' AS s50;
SELECT 'audit_logs client insert denied (only SECURITY DEFINER RPCs write)' AS s51;
SELECT 'Atomic rollback: invalid audience aborts create_event; no partial rows persisted' AS s52;

ROLLBACK;