import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";
import { unwrap } from "./_helpers";
import type { RegistrationCreateInput } from "@/lib/validation";

export type RegistrationRow = Database["public"]["Tables"]["registrations"]["Row"];

export async function createRegistration(
  input: Omit<RegistrationCreateInput, "lead">,
  createdBy: string | null = null,
): Promise<RegistrationRow> {
  const payload: Database["public"]["Tables"]["registrations"]["Insert"] = {
    registration_type: input.registration_type,
    lead_id: input.lead_id ?? null,
    project_id: input.project_id ?? null,
    product_id: input.product_id ?? null,
    voucher_id: input.voucher_id ?? null,
    event_id: input.event_id ?? null,
    note: input.note ?? null,
    created_by: createdBy,
    // registration_code is generated by DB trigger; empty string is overwritten.
    registration_code: "",
  };
  const res = await supabase.from("registrations").insert(payload).select("*").single();
  return unwrap(res, "registrations.create");
}

export async function listMyRegistrations(userId: string): Promise<RegistrationRow[]> {
  const res = await supabase
    .from("registrations")
    .select("*")
    .or(`created_by.eq.${userId},assigned_to.eq.${userId}`)
    .order("created_at", { ascending: false });
  return unwrap(res, "registrations.mine");
}