/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistrationsRouteImport } from './routes/registrations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VouchersVoucherIdRouteImport } from './routes/vouchers.$voucherId'
import { Route as RegistrationsRegistrationIdRouteImport } from './routes/registrations.$registrationId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as PoliciesPolicyIdRouteImport } from './routes/policies.$policyId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminInventoryTemplatesRouteImport } from './routes/admin.inventory-templates'
import { Route as AdminDevelopersRouteImport } from './routes/admin.developers'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminRegistrationsRegistrationIdRouteImport } from './routes/admin.registrations.$registrationId'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'
import { Route as AdminLeadsLeadIdRouteImport } from './routes/admin.leads.$leadId'
import { Route as AdminInventoryTemplatesTemplateIdRouteImport } from './routes/admin.inventory-templates.$templateId'
import { Route as AdminProjectsProjectIdEditRouteImport } from './routes/admin.projects.$projectId.edit'
import { Route as AdminProjectsProjectIdVouchersVoucherIdRouteImport } from './routes/admin.projects.$projectId.vouchers.$voucherId'
import { Route as AdminProjectsProjectIdProductsProductIdRouteImport } from './routes/admin.projects.$projectId.products.$productId'
import { Route as AdminProjectsProjectIdPoliciesPolicyIdRouteImport } from './routes/admin.projects.$projectId.policies.$policyId'
import { Route as AdminProjectsProjectIdEventsEventIdRouteImport } from './routes/admin.projects.$projectId.events.$eventId'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRoute = RegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VouchersVoucherIdRoute = VouchersVoucherIdRouteImport.update({
  id: '/$voucherId',
  path: '/$voucherId',
  getParentRoute: () => VouchersRoute,
} as any)
const RegistrationsRegistrationIdRoute =
  RegistrationsRegistrationIdRouteImport.update({
    id: '/$registrationId',
    path: '/$registrationId',
    getParentRoute: () => RegistrationsRoute,
  } as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPolicyIdRoute = PoliciesPolicyIdRouteImport.update({
  id: '/$policyId',
  path: '/$policyId',
  getParentRoute: () => PoliciesRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryTemplatesRoute = AdminInventoryTemplatesRouteImport.update({
  id: '/inventory-templates',
  path: '/inventory-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevelopersRoute = AdminDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminRegistrationsRegistrationIdRoute =
  AdminRegistrationsRegistrationIdRouteImport.update({
    id: '/$registrationId',
    path: '/$registrationId',
    getParentRoute: () => AdminRegistrationsRoute,
  } as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminLeadsLeadIdRoute = AdminLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminInventoryTemplatesTemplateIdRoute =
  AdminInventoryTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AdminInventoryTemplatesRoute,
  } as any)
const AdminProjectsProjectIdEditRoute =
  AdminProjectsProjectIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminProjectsProjectIdRoute,
  } as any)
const AdminProjectsProjectIdVouchersVoucherIdRoute =
  AdminProjectsProjectIdVouchersVoucherIdRouteImport.update({
    id: '/vouchers/$voucherId',
    path: '/vouchers/$voucherId',
    getParentRoute: () => AdminProjectsProjectIdRoute,
  } as any)
const AdminProjectsProjectIdProductsProductIdRoute =
  AdminProjectsProjectIdProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AdminProjectsProjectIdRoute,
  } as any)
const AdminProjectsProjectIdPoliciesPolicyIdRoute =
  AdminProjectsProjectIdPoliciesPolicyIdRouteImport.update({
    id: '/policies/$policyId',
    path: '/policies/$policyId',
    getParentRoute: () => AdminProjectsProjectIdRoute,
  } as any)
const AdminProjectsProjectIdEventsEventIdRoute =
  AdminProjectsProjectIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AdminProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/registrations': typeof RegistrationsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/vouchers': typeof VouchersRouteWithChildren
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/inventory-templates': typeof AdminInventoryTemplatesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/registrations': typeof AdminRegistrationsRouteWithChildren
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/registrations/$registrationId': typeof RegistrationsRegistrationIdRoute
  '/vouchers/$voucherId': typeof VouchersVoucherIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/inventory-templates/$templateId': typeof AdminInventoryTemplatesTemplateIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/registrations/$registrationId': typeof AdminRegistrationsRegistrationIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
  '/admin/projects/$projectId/events/$eventId': typeof AdminProjectsProjectIdEventsEventIdRoute
  '/admin/projects/$projectId/policies/$policyId': typeof AdminProjectsProjectIdPoliciesPolicyIdRoute
  '/admin/projects/$projectId/products/$productId': typeof AdminProjectsProjectIdProductsProductIdRoute
  '/admin/projects/$projectId/vouchers/$voucherId': typeof AdminProjectsProjectIdVouchersVoucherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/events': typeof EventsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/registrations': typeof RegistrationsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/vouchers': typeof VouchersRouteWithChildren
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/inventory-templates': typeof AdminInventoryTemplatesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/registrations': typeof AdminRegistrationsRouteWithChildren
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/registrations/$registrationId': typeof RegistrationsRegistrationIdRoute
  '/vouchers/$voucherId': typeof VouchersVoucherIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/inventory-templates/$templateId': typeof AdminInventoryTemplatesTemplateIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/registrations/$registrationId': typeof AdminRegistrationsRegistrationIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
  '/admin/projects/$projectId/events/$eventId': typeof AdminProjectsProjectIdEventsEventIdRoute
  '/admin/projects/$projectId/policies/$policyId': typeof AdminProjectsProjectIdPoliciesPolicyIdRoute
  '/admin/projects/$projectId/products/$productId': typeof AdminProjectsProjectIdProductsProductIdRoute
  '/admin/projects/$projectId/vouchers/$voucherId': typeof AdminProjectsProjectIdVouchersVoucherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/registrations': typeof RegistrationsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/vouchers': typeof VouchersRouteWithChildren
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/inventory-templates': typeof AdminInventoryTemplatesRouteWithChildren
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/registrations': typeof AdminRegistrationsRouteWithChildren
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/registrations/$registrationId': typeof RegistrationsRegistrationIdRoute
  '/vouchers/$voucherId': typeof VouchersVoucherIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/inventory-templates/$templateId': typeof AdminInventoryTemplatesTemplateIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/registrations/$registrationId': typeof AdminRegistrationsRegistrationIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
  '/admin/projects/$projectId/events/$eventId': typeof AdminProjectsProjectIdEventsEventIdRoute
  '/admin/projects/$projectId/policies/$policyId': typeof AdminProjectsProjectIdPoliciesPolicyIdRoute
  '/admin/projects/$projectId/products/$productId': typeof AdminProjectsProjectIdProductsProductIdRoute
  '/admin/projects/$projectId/vouchers/$voucherId': typeof AdminProjectsProjectIdVouchersVoucherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/events'
    | '/favorites'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/notifications'
    | '/policies'
    | '/projects'
    | '/register'
    | '/registrations'
    | '/reset-password'
    | '/unauthorized'
    | '/vouchers'
    | '/admin/developers'
    | '/admin/inventory-templates'
    | '/admin/leads'
    | '/admin/operations'
    | '/admin/projects'
    | '/admin/registrations'
    | '/admin/tasks'
    | '/admin/users'
    | '/events/$eventId'
    | '/policies/$policyId'
    | '/products/$productId'
    | '/projects/$projectId'
    | '/registrations/$registrationId'
    | '/vouchers/$voucherId'
    | '/admin/'
    | '/admin/inventory-templates/$templateId'
    | '/admin/leads/$leadId'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/registrations/$registrationId'
    | '/admin/users/$userId'
    | '/admin/projects/$projectId/edit'
    | '/admin/projects/$projectId/events/$eventId'
    | '/admin/projects/$projectId/policies/$policyId'
    | '/admin/projects/$projectId/products/$productId'
    | '/admin/projects/$projectId/vouchers/$voucherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/events'
    | '/favorites'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/notifications'
    | '/policies'
    | '/projects'
    | '/register'
    | '/registrations'
    | '/reset-password'
    | '/unauthorized'
    | '/vouchers'
    | '/admin/developers'
    | '/admin/inventory-templates'
    | '/admin/leads'
    | '/admin/operations'
    | '/admin/projects'
    | '/admin/registrations'
    | '/admin/tasks'
    | '/admin/users'
    | '/events/$eventId'
    | '/policies/$policyId'
    | '/products/$productId'
    | '/projects/$projectId'
    | '/registrations/$registrationId'
    | '/vouchers/$voucherId'
    | '/admin'
    | '/admin/inventory-templates/$templateId'
    | '/admin/leads/$leadId'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/registrations/$registrationId'
    | '/admin/users/$userId'
    | '/admin/projects/$projectId/edit'
    | '/admin/projects/$projectId/events/$eventId'
    | '/admin/projects/$projectId/policies/$policyId'
    | '/admin/projects/$projectId/products/$productId'
    | '/admin/projects/$projectId/vouchers/$voucherId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/events'
    | '/favorites'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/notifications'
    | '/policies'
    | '/projects'
    | '/register'
    | '/registrations'
    | '/reset-password'
    | '/unauthorized'
    | '/vouchers'
    | '/admin/developers'
    | '/admin/inventory-templates'
    | '/admin/leads'
    | '/admin/operations'
    | '/admin/projects'
    | '/admin/registrations'
    | '/admin/tasks'
    | '/admin/users'
    | '/events/$eventId'
    | '/policies/$policyId'
    | '/products/$productId'
    | '/projects/$projectId'
    | '/registrations/$registrationId'
    | '/vouchers/$voucherId'
    | '/admin/'
    | '/admin/inventory-templates/$templateId'
    | '/admin/leads/$leadId'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/registrations/$registrationId'
    | '/admin/users/$userId'
    | '/admin/projects/$projectId/edit'
    | '/admin/projects/$projectId/events/$eventId'
    | '/admin/projects/$projectId/policies/$policyId'
    | '/admin/projects/$projectId/products/$productId'
    | '/admin/projects/$projectId/vouchers/$voucherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PoliciesRoute: typeof PoliciesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  RegistrationsRoute: typeof RegistrationsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VouchersRoute: typeof VouchersRouteWithChildren
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vouchers/$voucherId': {
      id: '/vouchers/$voucherId'
      path: '/$voucherId'
      fullPath: '/vouchers/$voucherId'
      preLoaderRoute: typeof VouchersVoucherIdRouteImport
      parentRoute: typeof VouchersRoute
    }
    '/registrations/$registrationId': {
      id: '/registrations/$registrationId'
      path: '/$registrationId'
      fullPath: '/registrations/$registrationId'
      preLoaderRoute: typeof RegistrationsRegistrationIdRouteImport
      parentRoute: typeof RegistrationsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$policyId': {
      id: '/policies/$policyId'
      path: '/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof PoliciesPolicyIdRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory-templates': {
      id: '/admin/inventory-templates'
      path: '/inventory-templates'
      fullPath: '/admin/inventory-templates'
      preLoaderRoute: typeof AdminInventoryTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/developers': {
      id: '/admin/developers'
      path: '/developers'
      fullPath: '/admin/developers'
      preLoaderRoute: typeof AdminDevelopersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/registrations/$registrationId': {
      id: '/admin/registrations/$registrationId'
      path: '/$registrationId'
      fullPath: '/admin/registrations/$registrationId'
      preLoaderRoute: typeof AdminRegistrationsRegistrationIdRouteImport
      parentRoute: typeof AdminRegistrationsRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/leads/$leadId': {
      id: '/admin/leads/$leadId'
      path: '/$leadId'
      fullPath: '/admin/leads/$leadId'
      preLoaderRoute: typeof AdminLeadsLeadIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/inventory-templates/$templateId': {
      id: '/admin/inventory-templates/$templateId'
      path: '/$templateId'
      fullPath: '/admin/inventory-templates/$templateId'
      preLoaderRoute: typeof AdminInventoryTemplatesTemplateIdRouteImport
      parentRoute: typeof AdminInventoryTemplatesRoute
    }
    '/admin/projects/$projectId/edit': {
      id: '/admin/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/admin/projects/$projectId/edit'
      preLoaderRoute: typeof AdminProjectsProjectIdEditRouteImport
      parentRoute: typeof AdminProjectsProjectIdRoute
    }
    '/admin/projects/$projectId/vouchers/$voucherId': {
      id: '/admin/projects/$projectId/vouchers/$voucherId'
      path: '/vouchers/$voucherId'
      fullPath: '/admin/projects/$projectId/vouchers/$voucherId'
      preLoaderRoute: typeof AdminProjectsProjectIdVouchersVoucherIdRouteImport
      parentRoute: typeof AdminProjectsProjectIdRoute
    }
    '/admin/projects/$projectId/products/$productId': {
      id: '/admin/projects/$projectId/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/projects/$projectId/products/$productId'
      preLoaderRoute: typeof AdminProjectsProjectIdProductsProductIdRouteImport
      parentRoute: typeof AdminProjectsProjectIdRoute
    }
    '/admin/projects/$projectId/policies/$policyId': {
      id: '/admin/projects/$projectId/policies/$policyId'
      path: '/policies/$policyId'
      fullPath: '/admin/projects/$projectId/policies/$policyId'
      preLoaderRoute: typeof AdminProjectsProjectIdPoliciesPolicyIdRouteImport
      parentRoute: typeof AdminProjectsProjectIdRoute
    }
    '/admin/projects/$projectId/events/$eventId': {
      id: '/admin/projects/$projectId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/projects/$projectId/events/$eventId'
      preLoaderRoute: typeof AdminProjectsProjectIdEventsEventIdRouteImport
      parentRoute: typeof AdminProjectsProjectIdRoute
    }
  }
}

interface AdminInventoryTemplatesRouteChildren {
  AdminInventoryTemplatesTemplateIdRoute: typeof AdminInventoryTemplatesTemplateIdRoute
}

const AdminInventoryTemplatesRouteChildren: AdminInventoryTemplatesRouteChildren =
  {
    AdminInventoryTemplatesTemplateIdRoute:
      AdminInventoryTemplatesTemplateIdRoute,
  }

const AdminInventoryTemplatesRouteWithChildren =
  AdminInventoryTemplatesRoute._addFileChildren(
    AdminInventoryTemplatesRouteChildren,
  )

interface AdminLeadsRouteChildren {
  AdminLeadsLeadIdRoute: typeof AdminLeadsLeadIdRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsLeadIdRoute: AdminLeadsLeadIdRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminProjectsProjectIdRouteChildren {
  AdminProjectsProjectIdEditRoute: typeof AdminProjectsProjectIdEditRoute
  AdminProjectsProjectIdEventsEventIdRoute: typeof AdminProjectsProjectIdEventsEventIdRoute
  AdminProjectsProjectIdPoliciesPolicyIdRoute: typeof AdminProjectsProjectIdPoliciesPolicyIdRoute
  AdminProjectsProjectIdProductsProductIdRoute: typeof AdminProjectsProjectIdProductsProductIdRoute
  AdminProjectsProjectIdVouchersVoucherIdRoute: typeof AdminProjectsProjectIdVouchersVoucherIdRoute
}

const AdminProjectsProjectIdRouteChildren: AdminProjectsProjectIdRouteChildren =
  {
    AdminProjectsProjectIdEditRoute: AdminProjectsProjectIdEditRoute,
    AdminProjectsProjectIdEventsEventIdRoute:
      AdminProjectsProjectIdEventsEventIdRoute,
    AdminProjectsProjectIdPoliciesPolicyIdRoute:
      AdminProjectsProjectIdPoliciesPolicyIdRoute,
    AdminProjectsProjectIdProductsProductIdRoute:
      AdminProjectsProjectIdProductsProductIdRoute,
    AdminProjectsProjectIdVouchersVoucherIdRoute:
      AdminProjectsProjectIdVouchersVoucherIdRoute,
  }

const AdminProjectsProjectIdRouteWithChildren =
  AdminProjectsProjectIdRoute._addFileChildren(
    AdminProjectsProjectIdRouteChildren,
  )

interface AdminProjectsRouteChildren {
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRouteWithChildren
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRouteWithChildren,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminRegistrationsRouteChildren {
  AdminRegistrationsRegistrationIdRoute: typeof AdminRegistrationsRegistrationIdRoute
}

const AdminRegistrationsRouteChildren: AdminRegistrationsRouteChildren = {
  AdminRegistrationsRegistrationIdRoute: AdminRegistrationsRegistrationIdRoute,
}

const AdminRegistrationsRouteWithChildren =
  AdminRegistrationsRoute._addFileChildren(AdminRegistrationsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminDevelopersRoute: typeof AdminDevelopersRoute
  AdminInventoryTemplatesRoute: typeof AdminInventoryTemplatesRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminRegistrationsRoute: typeof AdminRegistrationsRouteWithChildren
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDevelopersRoute: AdminDevelopersRoute,
  AdminInventoryTemplatesRoute: AdminInventoryTemplatesRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminRegistrationsRoute: AdminRegistrationsRouteWithChildren,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface PoliciesRouteChildren {
  PoliciesPolicyIdRoute: typeof PoliciesPolicyIdRoute
}

const PoliciesRouteChildren: PoliciesRouteChildren = {
  PoliciesPolicyIdRoute: PoliciesPolicyIdRoute,
}

const PoliciesRouteWithChildren = PoliciesRoute._addFileChildren(
  PoliciesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface RegistrationsRouteChildren {
  RegistrationsRegistrationIdRoute: typeof RegistrationsRegistrationIdRoute
}

const RegistrationsRouteChildren: RegistrationsRouteChildren = {
  RegistrationsRegistrationIdRoute: RegistrationsRegistrationIdRoute,
}

const RegistrationsRouteWithChildren = RegistrationsRoute._addFileChildren(
  RegistrationsRouteChildren,
)

interface VouchersRouteChildren {
  VouchersVoucherIdRoute: typeof VouchersVoucherIdRoute
}

const VouchersRouteChildren: VouchersRouteChildren = {
  VouchersVoucherIdRoute: VouchersVoucherIdRoute,
}

const VouchersRouteWithChildren = VouchersRoute._addFileChildren(
  VouchersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PoliciesRoute: PoliciesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  RegistrationsRoute: RegistrationsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VouchersRoute: VouchersRouteWithChildren,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
